from enum import Enum

class LogType(Enum):
    # ✅ User Operations
    USER_REGISTERED = "USER_REGISTERED"
    USER_LOGGED_IN = "USER_LOGGED_IN"
    LOGIN_FAILED = "LOGIN_FAILED"
    USER_DELETED = "USER_DELETED"
    PASSWORD_RESET_LINK_SENT = "PASSWORD_RESET_LINK_SENT"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    USER_LOGGED_OUT = "USER_LOGGED_OUT"
    USER_UPDATED = "USER_UPDATED"
    USERNAME_CHANGED = "USERNAME_CHANGED"
    GOOGLE_LOGIN = "GOOGLE_LOGIN"

    # 💬 Conversations / Sessions
    CONVERSATION_STARTED = "CONVERSATION_STARTED"
    CONVERSATION_ENDED = "CONVERSATION_ENDED"
    CONVERSATION_TIMEOUT = "CONVERSATION_TIMEOUT"
    CONVERSATION_RESTORED = "CONVERSATION_RESTORED"
    CONVERSATION_TITLE_EDITED = "CONVERSATION_TITLE_EDITED"

    # 🤖 AI / Assistant
    AI_REPLY_GENERATED = "AI_REPLY_GENERATED"
    AI_TITLE_GENERATED = "AI_TITLE_GENERATED"
    AI_KEYWORDS_EXTRACTED = "AI_KEYWORDS_EXTRACTED"
    AI_RESPONSE_FAILED = "AI_RESPONSE_FAILED"
    CATEGORY_PREDICTED = "CATEGORY_PREDICTED"

    # 🛍️ Product Interaction
    PRODUCT_LIKED = "PRODUCT_LIKED"
    PRODUCT_UNLIKED = "PRODUCT_UNLIKED"
    PRODUCT_VIEWED = "PRODUCT_VIEWED"
    PRODUCT_SUGGESTION_SAVED = "PRODUCT_SUGGESTION_SAVED"

    # ⚠️ Security
    TOKEN_INVALID = "TOKEN_INVALID"
    PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED"

    # ⚠️ Category Assignment
    PRODUCT_CATEGORY_ASSIGNED_MANUAL = "PRODUCT_CATEGORY_ASSIGNED_MANUAL"
    CATEGORY_ASSIGNMENT_FAILED = "CATEGORY_ASSIGNMENT_FAILED"